### ISSUE TITLE
Discuss the naming of Various Stores and need for different types of stores inside Veraison kvstore

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/veraison#151]
Current implementation (as of 06/04/2022) has Endorsement Store and TrustAnchorStore.

Need to decide where Certification will reside? A separate store or part of Endorsement Store ?

Any other new types added(like SW Updates) needs a addition of stores.

Also the naming is confusing.

TrustAnchor are also a type of Endorsements. So how does the names uniquely identify the type of elements stored in the Store Type?

Need to discuss the same, via this issue and make a suitable change in the code base..

**Comment by setrofim** [comment]
My two cents on this:

I don't think the number of stores needs to be an architectural issue, i.e. be reflected in the APIs.  A single endorsement method as (suggested here https://github.com/veraison/veraison/pull/148#discussion_r843827241) should be enough with a filed within the Endorsement structure used to distinguish between the endorsement types.  This "type" field can also be included in the ID URI, thus disambiguating the cases where  a scheme uses the same ID derivation for  trust anchor and a reference value set.

**Comment by yogeshbdeshpande** [comment]
See also Issue #152

**Comment by yogeshbdeshpande** [comment]
Resolved as it is decided to keep all Endorsements under one Umbrella for now!
