### ISSUE TITLE
feature: need a build environment available in a Docker container

### ISSUE THREAD

**Issue by dreemkiller** [veraison/veraison#161]
### Is your feature request related to a problem? Please describe

The instructions in the `BUILD.md` file presume the user has a properly configured environment set up. While setting up this environment is fairly easy, if the user moves to a new system, the set up needs to be done again.

### If possible, describe a solution

I have implemented one for myself here: https://github.com/dreemkiller/veraison_docker

Basically, it has a Dockerfile that sets up the environment, and a Makefile that builds the docker container, runs it while attaching the `veraison` directory to it, and allows the user to start a shell in the running container.

### Describe alternatives you have considered

Another possibility is to provide instructions on how to set up the environment. However, these steps would need to be done for every platform the user needed to build on. The industry seems to be trending towards docker for these cases instead.

## Additional context

I've found it helpful to not rely on prebuilt docker images that contain the golang toolset, as if you need to integrate your `golang` dockerfile into another project's docker files, it's not clear all that needs to be done.

**Comment by yogeshbdeshpande** [comment]
Work in progress via: https://github.com/veraison/services/pull/57

**Comment by thomas-fossati** [comment]
> Work in progress via: [veraison/services#57](https://github.com/veraison/services/pull/57)

I think @dreemkiller is proposing something different here: a docker-based dev environment rather than a docker-based integration / test / demo environment.

**Comment by dreemkiller** [comment]
Yes, that is what I am proposing. I have one here: https://github.com/dreemkiller/veraison_docker that currently suits my purposes (works with VS code Remote Tools). Not sure if it would suit others, though.

**Comment by dreemkiller** [comment]
Note that the above docker image is `aarch64`-specific. Some (small?) amount of work would need to be done to make it arch independent.

**Comment by yogeshbdeshpande** [comment]
Issue now tracked via:
https://github.com/veraison/services/issues/88
