### ISSUE TITLE
feature: architectural support for verifying linked evidences

### ISSUE THREAD

**Issue by artoniemi** [veraison/veraison#167]
It is often necessary to verify multiple attestation evidences from the same attester in order to appraise the trustworthiness of the system as a whole. For example, there may be a separate attestation evidence for each layer in a layered system. There should be a convenient way to verify that a set of evidences comes from the same attester, e.g. that they all contain the same challenge / nonce. Currently, there is no easy way to do this in the verification plugin, especially if the linked evidences are presented for verification one-by-one.

**Comment by thomas-fossati** [comment]
IIUC, this may be achieved by modifying the challenge-response API to accept more than one evidence under the same session object, which is where the nonce resides.

**Comment by yogeshbdeshpande** [comment]
Issue now tracked via:
https://github.com/veraison/services/issues/89
