### ISSUE TITLE
Add test for the policy engine based on OPA

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/veraison#17]
At the moment, the policy engine built on OPA has no tests.

**Comment by yogeshbdeshpande** [comment]
@thomas-fossati This is addressed in https://github.com/veraison/services/commit/51e90b5130df8618385ae4c339eed73351108161

Could you please confirm?

**Comment by thomas-fossati** [comment]
As we speak, the veraison/services/policy bit has 73.7% coverage, so I'd say it's drastically improved.  There is always room to increase and better our testing but we have https://github.com/veraison/services/issues/59 to track that.  I'd consider this specific issue closed.
