### ISSUE TITLE
feature: Add tooling

### ISSUE THREAD

**Issue by setrofim** [veraison/veraison#23]
### Is your feature request related to a problem? Please describe

Debugging the demo implementation of the front end highlighted significant difficulties in working data used for testing. Part of the issue is due to the current lack of provisioning path. However, even if that existed, most of these difficulties would remain to some extent. Specific pain points identified:

- Difficulty in manually comparing endorsements and evidence extracted from a token.
- Difficulty in updating and testing a policy against a specific set of endorsements and evidence.
- Difficulty in updating the stores with modifications to endorsements/policy.

### If possible, describe a solution

A few CLI tools, implemented on top of the same components as the service, that allow:

- Query and update endorsements.
- Query and update trust anchors.
- Query and update policies.
- Execute a policy against specifically-crafted inputs.

As part of this, it would also make sense to implement a common configuration mechanism that would be used to resolve things such as plugin and store locations by the tools, as well as the service, removing the need for them to be provided each time on invocation.

### Describe alternatives you have considered

As mentioned above, once the provisioning flows have been implemented certain things will be easier (specifically, updating the stores). Improved logging would also help here. However, it would still be useful to have a set of small, lightweight CLI tools that allow working on individual steps without having to go through the entire flow for a tighter REPL during development.

### Additional context

N/A

**Comment by yogeshbdeshpande** [comment]
https://github.com/veraison/services/issues/72 will now track this!
