### ISSUE TITLE
feature: TEEP token

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/veraison#24]
### Is your feature request related to a problem? Please describe

At present we only support verification of one kind of EAT-based Evidence, namely the PSA token.  While the SW architecture has been designed with the explicit goal of supporting different Evidence syntaxes and semantics, having a second use case to prove the theory is correct would be an excellent test bed.  More so, if it supports a real use case rather than a synthetic one.

### If possible, describe a solution

The TEEP token:

* [TEEP Evidence](https://datatracker.ietf.org/doc/html/draft-ietf-teep-protocol-05#section-4.3.1)
* [SUIT claims](https://tools.ietf.org/html/draft-birkholz-rats-suit-claims-01)
* [Example](https://datatracker.ietf.org/doc/html/draft-ietf-teep-protocol-05#appendix-D.3)

would be an ideal candidate.

We should provide support for it both in the verification pipeline, as well as a standalone package a la [veraison/psatoken](https://github.com/veraison/psatoken).

### Describe alternatives you have considered

We considered using the [QWES token](https://tools.ietf.org/html/draft-mandyam-rats-qwestoken-00) but the spec is not actively maintained and there are important details missing.

We considered creating a synthetic token.  While this option has been parked for the time being, we might want to resume it in the future in order to stress some of the advanced features that we want to support (e.g., evidence encryption, nested verification, etc.), which are not currently required in existing standards.

## Additional context

No additional context.

**Comment by thomas-fossati** [comment]
This story is starting to have interesting ramifications.  In the TEEP meeting today there has been discussion around the [freshness model]() to use for the attestation.

**Comment by yogeshbdeshpande** [comment]
Issue now tracked using:
https://github.com/veraison/services/issues/85
