### ISSUE TITLE
feature: endorsement provisioning API

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/veraison#25]
### Is your feature request related to a problem? Please describe

We have not yet defined an API for the provisioning of endorsements.

### If possible, describe a solution

We should design an interface that

* is able to support different endorsement formats;
* is able to ingest multiple endorsements in one call;
* supports synchronous and asynchronous status notifications.

The design should be formalised as an OpenAPI document in the [docs/api](https://github.com/veraison/veraison/tree/main/docs/api) folder.

### Describe alternatives you have considered

No alternatives have been considered.

## Additional context

No additional context provided.

**Comment by yogeshbdeshpande** [comment]
@thomas-fossati I think, we have addressed the requirement mentioned in this issue?
