### ISSUE TITLE
feature: attestation result format

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/veraison#27]
### Is your feature request related to a problem? Please describe

At present, the [challenge-response API](https://github.com/veraison/veraison/blob/main/docs/api/README.md) returns the attestation result in form of "naked" JSON object with a custom / free-form format.

There are two aspects to address here:
1. moving from custom / free-form to something that is more stable;
2. allow attestation results to be signed by the attester.

We should move towards the model defined by the RATS architecture [bow tie diagram](https://www.ietf.org/archive/id/draft-ietf-rats-architecture-10.html#figure-9):

```
                Evidence           Attestation Results
.--------------.   CWT                    CWT   .-------------------.
|  Attester-A  |------------.      .----------->|  Relying Party V  |
'--------------'            v      |            `-------------------'
.--------------.   JWT   .------------.   JWT   .-------------------.
|  Attester-B  |-------->|  Verifier  |-------->|  Relying Party W  |
'--------------'         |            |         `-------------------'
.--------------.  X.509  |            |  X.509  .-------------------.
|  Attester-C  |-------->|            |-------->|  Relying Party X  |
'--------------'         |            |         `-------------------'
.--------------.   TPM   |            |   TPM   .-------------------.
|  Attester-D  |-------->|            |-------->|  Relying Party Y  |
'--------------'         '------------'         `-------------------'
.--------------.  other     ^      |     other  .-------------------.
|  Attester-E  |------------'      '----------->|  Relying Party Z  |
'--------------'                                `-------------------'
```

### If possible, describe a solution

1. Define the format of Veraison attestation results
    1. Document it publicly (e.g., in the relevant OpenAPI component's schema, and/or in an Internet draft);
    2. Register the associated MIME format (e.g., `application/vnd.veraison-attestation-result+json`);
    3. Adapt codebase.
3. Define a signed envelope that can be used to carry it (maybe we could use JWT and CWT always, with optional signature)

### Describe alternatives you have considered

No alternatives have been considered for the moment.

## Additional context

* [Consideration for using "none" algorithm in JWT](https://tools.ietf.org/html/rfc8725#section-3.2)
* [Unprotected CWTs](https://tools.ietf.org/html/draft-birkholz-rats-uccs)

**Comment by SimonFrost-Arm** [comment]
As part of this I propose discussing whether a standardised / normalised approach to the set of claims in the results would be effective for a majority of tokens. This has not been covered by any standards body yet, though seems appropriate for future RATS / CCC-AAA discussion and having a Veraison opinion in advance seems valuable.
Note Microsoft Azure Attestation service using some commonality here: https://docs.microsoft.com/en-us/azure/attestation/claim-sets

**Comment by thomas-fossati** [comment]
Nice!  Another good example (although for a slightly niche use case) is the [trustworthiness vector](https://tools.ietf.org/id/draft-voit-rats-trustworthy-path-routing-01.html#section-3.4) for trusted path routing.

**Comment by yogeshbdeshpande** [comment]
Please see: https://github.com/veraison/services/issues/65
