### ISSUE TITLE
feature: provide a non-plugin implementation of the Veraison internal interfaces

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/veraison#28]
### Is your feature request related to a problem? Please describe

At present, all implementations of Veraison's internal interfaces are based on [hashicorp go plugin](https://github.com/hashicorp/go-plugin).  In theory, we are not tied to a specific implementation model, not even the completely decoupled, RPC-based interface provided by the go-plugin.  We should prove this with running code.

### If possible, describe a solution

Implement Veraison interfaces by means of "local" types only.

### Describe alternatives you have considered

This is the alternative :-)

## Additional context

No additional context.

**Comment by yogeshbdeshpande** [comment]
Now tracked by:
https://github.com/veraison/services/issues/76
