### ISSUE TITLE
contact method for reporting abusive behaviour

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/veraison#35]
In our code of conduct the contact point for reporting abusive behaviours is a stub.  It should instead resolve to some kind of private channel that is terminated by the appropriate individual/s.

_For further context, see also https://github.com/veraison/veraison/pull/34#discussion_r592435449_

**Comment by yogeshbdeshpande** [comment]
@thomas-fossati If this is still applicable can we move this to community repository?

**Comment by thomas-fossati** [comment]
the [CoC](https://github.com/veraison/.github/blob/main/CODE_OF_CONDUCT.md) is currently hosted at the veraison organisation level, and the stub mentioned in this issue is now a real email address.  The thing is that in the meantime we moved away from the @arm.com contact point to https://groups.google.com/g/veraison-project/settings, so we should update that.

**Comment by yogeshbdeshpande** [comment]
Further work tracked via:
https://github.com/veraison/services/issues/82
