### ISSUE TITLE
BUG: REST API should not embed versioning in the URL

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/veraison#36]
API versioning should not be embedded in the URL.  It should be in the media type instead:

https://github.com/veraison/veraison/blob/4c2a725d1c374d50811a6f75f08561546c4749b1/docs/api/challenge-response.yaml#L9

**Comment by yogeshbdeshpande** [comment]
Issue tracked via:
https://github.com/veraison/services/issues/73
