### ISSUE TITLE
DOCS: Introduce Endorsement Provisioning API 

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/veraison#60]
This issue tracks creation of Endorsement Provisioning API, under docs/api folder.

**Comment by thomas-fossati** [comment]
#61 deals with the submission of one CoRIM.  We probably need to handle the case of multiple CoRIMs submitted with one single POST too.

**Comment by thomas-fossati** [comment]
> #61 deals with the submission of one CoRIM. We probably need to handle the case of multiple CoRIMs submitted with one single POST too.

Discussed during today's public meeting.  We don't need this now.

**Comment by yogeshbdeshpande** [comment]
Closing this, as we do not need this for now!
