### ISSUE TITLE
Feature:  Consider creating a Docker for GitHub Actions

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/veraison#83]
Currently Github Actions run each action independently. This creates individual jobs (For CI, Cover and Lint), each have its own separate dependency files. This leads to a lot of duplication.

Using 
https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action 
One can containerize each action where identical stuff can be inherited and dependencies managed in a better way!

**Comment by thomas-fossati** [comment]
this looks like a dup of #81

**Comment by yogeshbdeshpande** [comment]
Yes, I do not get a notification when you create an issue, so was un-sure whether such an issue exists or not?

Let me close this!
